[versions]
minecraft = "1.12.2"
yarn_build = "541"
fabric_loader = "0.15.11"
loom = "1.7-SNAPSHOT"
legacy-looming = "1.7-SNAPSHOT"
vineflower = "1.10.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
legacy_looming = { id = "legacy-looming", version.ref = "legacy-looming" }
