[versions]
minecraft = "1.16.1"
yarn_mappings = "1.16.1-build.22"
fabric_loader = "0.15.11"
loom = "1.6-SNAPSHOT"
vineflower = "1.11.0-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn_mappings = { module = "dev.tildejustin:yarn", version.ref = "yarn_mappings" }
# yarn_mappings = { module = "net.fabricmc:yarn", version.ref = "yarn_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
